title: Projects - Cyrox Softech
email: contact@cyroxsoftech.com
description: >- # this means to ignore newlines until "baseurl:"
  This website contains list of all the open source repositories on github by Cyrox Softech.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://opensource.cyroxsoftech.com" # the base hostname & protocol for your site, e.g. http://example.com
about_url: https://cyroxsoftech.com
twitter_username: cyroxsoftech
github_username: cyroxsoftech
author: Cyrox Softech
lang: en-US
# google_analytics: UA-89128710-4

timezone: Africa/Abidjan

# Build settings
markdown: kramdown
plugins:
#  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
#  - jekyll-mentions
#  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
  - screenshot.png
